// <auto-generated />
namespace Projekat.Migrations.VestiContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Dodavanje_Vesti_U_Bazu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dodavanje_Vesti_U_Bazu));
        
        string IMigrationMetadata.Id
        {
            get { return "201808170921538_Dodavanje_Vesti_U_Bazu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
