// <auto-generated />
namespace Projekat.Migrations.VestiContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DodavanjeDatumaICuvaSePutDoSlike : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodavanjeDatumaICuvaSePutDoSlike));
        
        string IMigrationMetadata.Id
        {
            get { return "201808220807445_DodavanjeDatumaICuvaSePutDoSlike"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
