// <auto-generated />
namespace Projekat.Migrations.MaterijalContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removePredmetModel_predmetId_part2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removePredmetModel_predmetId_part2));
        
        string IMigrationMetadata.Id
        {
            get { return "201801101046249_removePredmetModel_predmetId_part2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
