// <auto-generated />
namespace Projekat.Migrations.MaterijalContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ForumMEssage4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForumMEssage4));
        
        string IMigrationMetadata.Id
        {
            get { return "201909020949558_ForumMEssage4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
