// <auto-generated />
namespace Projekat.Migrations.MaterijalContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ForumPokusaj2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForumPokusaj2));
        
        string IMigrationMetadata.Id
        {
            get { return "201907081425002_ForumPokusaj2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
